feat: add MainTitle/SearchBtn/TextDesc components
u1timaD/sp_react pull request #1
Opened 2024-03-31 12:19 UTC by u1timaD

2024-04-23 13:15 UTC, Webappmaster-Eugene requested changes
Кое-что поправим и будет отлично! В цклом очень хорошая работа!

2024-04-23 13:15 UTC, Webappmaster-Eugene commented on src/Layouts/Home/Home.jsx
> +        style={{
Фу-фу такое) Давайте отдельный файлик css сделаем?

2024-04-23 13:15 UTC, Webappmaster-Eugene commented on src/App.css
>  .logo {
С анимацией хорошая идея!

2024-04-23 13:15 UTC, Webappmaster-Eugene commented on src/components/Input/input.module.css
> +.input {
НАЗВАНИЕ самого файла должно быть везде с одинаковым написанием (с большой буквы)

2024-04-23 13:15 UTC, Webappmaster-Eugene commented on src/components/Input/Input.jsx
> +    <>
Хорошее решение!

2024-04-23 14:35 UTC, u1timaD commented on src/App.css
>  .logo {
Немного не понял, на счет анимации🙇‍♂️

2024-04-23 21:09 UTC, u1timaD commented on src/components/Input/Input.jsx
> +    <>
Да, я хотел сделать единый компонент для инпута, но немного запутался в реализации и сделал отдельный компонент для поиска.

2024-04-24 05:07 UTC, Webappmaster-Eugene commented
Сейчас вопросов нет, отлично!

2024-04-24 05:07 UTC, merged